---
title: "BioDT biodiversity model"
date: "`r Sys.Date()`"
output: html_document
params:
  taxonkey: 5334220
  out_file: "untitled.tif"
  n_bootraps: 5
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages

```{r packages, warning=FALSE}
#spatial
library(terra)
library(sf)

#statistical
library(tidymodels)

#getting gbif data
library(rgbif)

#spatial thinning
library(spThin)

#data manipulation
library(dplyr)

set.seed(42)

```

## Load data

### Species data from GBIF

```{r load_gbif_data}
#get the GBIF data from the API
gbif_data <- occ_data(taxonKey = params$taxonkey,
         gadmGid = "GBR.3_1", # scotland
         limit=10000,
         coordinateUncertaintyInMeters='0,101',
         occurrenceStatus = NULL,
         hasCoordinate=TRUE,
         hasGeospatialIssue=FALSE)

#get the appropriate columns
gbif_data <- gbif_data$data %>% select(key, 
                                       scientificName, 
                                       decimalLatitude,
                                       decimalLongitude,
                                       datasetKey,
                                       publishingOrgKey,
                                       coordinateUncertaintyInMeters,
                                       year,
                                       month,
                                       day,
                                       license,
                                       recordedBy,
                                       identifiedBy,
                                       rightsHolder
                                       )

gbif_xy <- gbif_data %>% select(x = decimalLongitude,y = decimalLatitude)

#Species name
print(gbif_data$scientificName %>% first())
```

### Environmental

```{r load_environmental_data}
#Currently loading a raster file locally but this could be upgraded to any other raster
env_data <- rast("inputs/env-layers.tif")


```















## Export

Export the model the output file location provided to the parametised markdown

```{r export}
# 2 band raster
# mod_predictions$sd model varience
# mod_predictions$mean mean across boostraps

mod_predictions %>% writeRaster(params$out_file,overwrite=T)
```


## Session info

```{r session_info}
sessionInfo()
```

